<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActiveByAlias($alias)
    {
        return $this
            ->createQueryBuilder('product')
            ->where("product.alias = :alias")
            ->andWhere('product.active = :active')
            ->setParameter('alias', $alias)
            ->setParameter('active', 1)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }

    public function findByProductsExisting()
    {
        return $this
            ->createQueryBuilder('category')
            ->leftJoin(
                'AppBundle:Product',
                'product',
                \Doctrine\ORM\Query\Expr\Join::WITH,
                'category = product.category'
            )
            ->where("product.active = :active")
            ->andWhere('category.active = :active')
            ->andWhere('product.category = category')
            ->setParameter('active', 1)
            ->orderBy('category.title', 'ASC')
            ->getQuery()
            ->getResult()
            ;
    }
}
