<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActiveByAlias($alias)
    {
        return $this
            ->createQueryBuilder('product')
            ->where("product.alias = :alias")
            ->andWhere('product.active = :active')
            ->setParameter('alias', $alias)
            ->setParameter('active', 1)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
