<?php

namespace AppBundle\Repository;

/**
 * OrderSimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderSimRepository extends \Doctrine\ORM\EntityRepository
{
}
